- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ./files/api.sh
    dest: /home/centos/market-place-api
    owner: centos
    group: centos
    mode: '0777'

- name: Build and run docker container
  ansible.builtin.shell:
    chdir: /home/centos/market-place-api
    cmd: ./api.sh
  args:
    executable: /bin/bash