- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ./files/api.sh
    dest: /home/centos/market-place-api
    owner: root
    group: root
    mode: '0666'

- name: Build and run docker container
  ansible.builtin.shell:
    chdir: /home/centos/market-place-api
    cmd: ./api.sh
  args:
    executable: /bin/bash