- name: Fetch the data from git repo
  ansible.builtin.git:
    repo: git@github.com:dev-bishal1/market-place-api.git
    dest: /home/centos/

- name: Build and run docker container
  ansible.builtin.shell:
    chdir: /home/centos/market-place-api
    cmd: ./files/api.sh
  args:
    executable: /bin/bash

