- name: Webserver Setup
  hosts: websrvrgroup
  become: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Start httpd 
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install wget and unzip
      yum: 
        name: "{{ packages }}"
        state: present
      vars: 
        packages:
          - wget
          - unzip

- name: Copy the website setup file to the remote machine 
  hosts: websrvrgroup
  become: yes
  tasks:
    - name: Fetch website template from tooplate and serve them using httpd
      copy:
        src: website_setup.sh
        dest: /home/centos/
        owner: centos
        mode: 0777

- name: Website Setup
  hosts: websrvrgroup
  become: yes
  tasks: 
    - name: Execute the script that setup the website
      ansible.builtin.shell:
          chdir: /home/centos/
          cmd: ./website_setup.sh
