- name: Webserver Setup
  hosts: websrvrgroup
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name:
          - httpd
          - wget
          - unzip
        state: present

    - name: Start and enable the httpd service
      service:
        name: httpd
        state: started
        enabled: yes


- name: Copy and Execute Website Setup Script
  hosts: web01:web02
  become: yes
  tasks:
    - name: Copy the setup file
      copy:
        src: "{{ item.src }}"
        dest: /home/centos/
        owner: centos
        mode: 0777
      with_items:
        - { src: 'barista_website_setup.sh' }
        - { src: 'gotto_job_website_setup.sh' }

    - name: Execute the website setup script
      ansible.builtin.shell:
        chdir: /home/centos/
        cmd: "./{{ item.script }}"
      with_items:
        - { script: 'barista_website_setup.sh' }
        - { script: 'gotto_job_website_setup.sh' }
