- name: Update package manager cache for debain os
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Add the EPEL repository incase nginx is not available in offical redhat repository
  yum:
    name: epel-release
    state: present
  when: ansible_pkg_mgr == "yum"
  
- name: Install nginx package in redhat os
  yum: 
    name: nginx
    state: present
  when: ansible_pkg_mgr == "yum"
  notify:
    - Start and enable nginx server

- name: Install nginx package on debian os
  apt:
    name: nginx
    state: present
  when: ansible_pkg_mgr == "apt"
  notify:
    - Start and enable nginx server
