- name: Update package manager cache for debain os
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Add the EPEL repository incase installing package is not available in offical redhat repository
  yum:
    name: epel-release
    state: present
  when: ansible_pkg_mgr == "yum"
  