- name: AWS related configuration
  hosts: localhost
  gather_facts: False
  tasks:
    - name: create a new ec2 key pair, returns generated private key
      ec2_key:
        name: test-key-pair
        region: us-east-1
      register: keyout

    # - name: Debug the generated key
    #   debug:
    #     var: keyout
      
    - name: Save the generated private key to the file
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./test-key-pair.pem
      when: keyout.changed

    - ec2_instance:
        key_name: test-key-pair
        instance_type: t2.micro
        image_id: ami-0230bd60aa48260c6
        region: us-east-1
        wait: yes
        exact_count: 1
        instance_tags:
          Name: machine_01
        count_tag:
          Name: machine_01
