- name: AWS related configuration
  hosts: localhost
  gather_facts: False
  tasks:
    - name: create a new ec2 key pair, returns generated private key
      ec2_key:
        name: test-key-pair
        region: us-east-1
      register: keyout

    - name: Debug the generated key
      debug:
        var: keyout
