- name: Install ntp service
  hosts: all
  become: yes
  tasks:
    - name: Install ntp on centos machine
      yum:
        name: "{{ item }}"
        state: present
      when: ansible_pkg_mgr == "yum"
      loop:
        - ntp
        - wget
        - curl

    
    - name: Install npt on ubuntu machine
      apt:
        name: "{{ item }}"
        state: present
      when: ansible_pkg_mgr == "apt"
      loop:
        - ntp
        - wget
        - curl

    - name: Start and enable ntpd service in centos
      service:
        name: ntpd
        state: started
        enabled: true
      when: ansible_os_family == "RedHat"

    - name: Start and enable ntp service in ubuntu
      service:
        name: ntp
        state: started
        enabled: true
      when: ansible_os_family == "Debian"

    - name: Add group to all the host machine
      group:
        name: devops
        state: present
    
    - name: Add user to all the host machine
      user:
        name: "{{ usernames }}"
        groups: devops
        shell: /bin/bash
