- name: Ansible template testing
  hosts: all
  become: yes
  vars: 
    user_name: Bishal Rayamajhi
  tasks:
    - name: Install httpd in centos machine
      yum:
        name: httpd
        state: present
      when: ansible_pkg_mgr == "yum"

    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == "apt"
    
    - name: Install apache2 in ubuntu machine
      apt:
        name: apache2
        state: present
      when: ansible_pkg_mgr == "apt"

    - name: Start and enable httpd service in centos machine
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start and enable apache2 service in ubuntu machine
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Replace the apache default page in centos machine with custom template
      template:
        src: templates/welcome.j2
        dest: /var/www/html/index.html
        mode: '0644'
        owner: root
      when: ansible_os_family == "RedHat"
      notify: Restart httpd server

    - name: Replace the apache default page in ubuntu machine with custom template
      template:
        src: templates/welcome.j2
        dest: /var/www/html/index.html
        mode: '0644'
        owner: root
      when: ansible_os_family == "Debian"
      notify: Restart apache2 server

  handlers:
    - name: Restart apache2 server
      service:
        name: apache2
        state: restarted
    
    - name: Restart httpd server
      service:
        name: httpd
        state: restarted

  

